import { getPersonById } from "@/lib/person/fetch";


interface Props {
  params: { person_id: string }
}

export default async function Head({ params: { person_id } }: Props) {
  const { name } = await getPersonById(person_id);
  
  return (
    <>
      <title>{`${ name } ${"\u2022"} ${ process.env.NEXT_PUBLIC_APP_NAME }` }</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}