import { getGenreById } from "@/lib/genre/fetch"

interface HeadProps { 
  params: { id: string } 
}

export default async function Head({ params: { id } }: HeadProps) {
  const { name } = await getGenreById(id)
  
  return (
    <>
      <title>{`Films of ${ name } ${"\u2022"} ${ process.env.NEXT_PUBLIC_APP_NAME }` }</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}