import { getFilmById } from "@/lib/films/fetch";

interface Props {
  params: { movie_id: string }
}

export default async function Head({ params: { movie_id } }: Props): Promise<JSX.Element> {
  const { title, release_date } = await getFilmById(movie_id);
  
  return (
    <>
      <title>{`${ title } (${ release_date.substr(0,4) }) - Cast & Crew ${"\u2022"} ${ process.env.NEXT_PUBLIC_APP_NAME }` }</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}