async function getFilmTitle(slug: string) {
  const res = await fetch(`${ process.env.NEXT_PUBLIC_HOST }/api/v1/films/${slug}`);
  return res.json();
}

export default async function Head({ params }: { params: { slug: string } }) {
  const { title, year } = await getFilmTitle(params.slug);
  
  return (
    <>
      <title>{`${ title } (${ year }) ${"\u2022"} ${ process.env.NEXT_PUBLIC_APP_NAME }` }</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}