import { getFilmBySlug } from "@/lib/films/utils";

interface Props {
  params: { slug: string }
}

export default async function Head({ params }: Props) {
  const { title, year } = await getFilmBySlug(params.slug);
  
  return (
    <>
      <title>{`${ title } (${ year }) ${"\u2022"} ${ process.env.NEXT_PUBLIC_APP_NAME }` }</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}